---
title: "Oto_stats"
author: "TR"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(ggplot2)
library(knitr)
library(lubridate)
library(data.table)
```

```{r cleanup raw SIMS, include=FALSE, echo=FALSE, eval=FALSE}
#script for cleaning up SIMS files from GFZ, may need to be changed according to data structure
rm(list = ls())

Oto_all <- read.delim("Sample_2022/Oto_2022_SIMS_raw_part1.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

#Eliminate point measurements for e.g., pilot
#Oto_all <- Oto_all[Oto_all$Type..Tr.Pt. != "Pt",]

unique(substr(Oto_all$Analysis, 1,2))


#cleanup, deactivate measurement_inv if columns contain "core" and "margin" values
Otopike <- Oto_all %>%
  transmute(measurement = as.numeric(substr(Analysis, nchar(Analysis)-1, nchar(Analysis))),
            ID = substr(Analysis, 1,2),
            #ID2 = Otolith.number,
            #date = lubridate::as_date(parse_date_time(Date, orders = c("dmy"))),
            d18O = 0.97001 * as.numeric(d18O.SMOW) -29.99,
            x = east.west..um.,
            y = north.south..um.,
            SE_permil = X1SE..permil.,
            #SE_percent = X1SE....,
            OH = X16O1H.16O.measured)%>%
  group_by(ID)%>%
  mutate(measurement_inv = order(desc(measurement)))


#Order to avoid disaster
Otopike <- Otopike[order(Otopike$ID),]

#Calculate Distances
IDOto <- unique(Otopike$ID)

Dist <- NULL

for (i in 1:length(IDOto)){
  d <- sqrt(((sqrt(Otopike[which(Otopike$ID == IDOto[i]),]$x^2)) - 
               (sqrt((Otopike[which(Otopike$ID == IDOto[i] & Otopike$measurement == 1),]$x)^2)))^2 +
              ((sqrt(Otopike[which(Otopike$ID == IDOto[i]),]$y^2)) - 
                 (sqrt((Otopike[which(Otopike$ID == IDOto[i] & Otopike$measurement == 1),]$y)^2)))^2)

  Dist <- c(Dist, d)
}

Otopike$Distance_um <- Dist

#Check for hickups
Otopike[Otopike$measurement == 1,]$Distance_um

#This isn´t even my final form
Oto_distances2 <- Otopike %>%
  transmute(ID = ID,
            #ID2 = ID2,
            #measurement=measurement,
            #date = date,
            Distance_um = Distance_um,
            d18O = d18O,
            OH = OH,
            SE_permil = SE_permil)%>%
  group_by(ID)%>%
  arrange(desc(Distance_um))

write.table(Oto_distances, file = "Otolith_data_2022_clean_with_distance_um.txt", dec = ".", sep = ";", row.names = FALSE)
```

```{r cleanup core SIMS, include=FALSE, echo=FALSE, eval=FALSE}
#script for cleaning up SIMS files from GFZ, may need to be changed according to data structure
rm(list = ls())

Oto_all <- read.delim("Sample_2022/Oto_2022_SIMS-core_part2.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

#Eliminate point measurements for e.g., pilot
#Oto_all <- Oto_all[Oto_all$Type..Tr.Pt. != "Pt",]

unique(substr(Oto_all$Analysis, 1,2))


#cleanup, deactivate measurement_inv if columns contain "core" and "margin" values
Otopike <- Oto_all %>%
  transmute(measurement = as.numeric(substr(Analysis, nchar(Analysis)-1, nchar(Analysis))),
            ID = substr(Analysis, 1,2),
            #ID2 = Otolith.number,
            #date = lubridate::as_date(parse_date_time(Date, orders = c("dmy"))),
            d18O = 0.97001 * as.numeric(d18O.SMOW) -29.99,
            x = east.west..um.,
            y = north.south..um.,
            SE_permil = X1SE..permil.,
            #SE_percent = X1SE....,
            OH = X16O1H.16O.measured)%>%
  group_by(ID)%>%
  mutate(measurement_inv = order(desc(measurement)))


#Order to avoid disaster
Otopike <- Otopike[order(Otopike$ID),]

#Calculate Distances
IDOto <- unique(Otopike$ID)

Dist <- NULL

for (i in 1:length(IDOto)){
  d <- sqrt(((sqrt(Otopike[which(Otopike$ID == IDOto[i]),]$x^2)) - 
               (sqrt((Otopike[which(Otopike$ID == IDOto[i] & Otopike$measurement == 1),]$x)^2)))^2 +
              ((sqrt(Otopike[which(Otopike$ID == IDOto[i]),]$y^2)) - 
                 (sqrt((Otopike[which(Otopike$ID == IDOto[i] & Otopike$measurement == 1),]$y)^2)))^2)

  Dist <- c(Dist, d)
}

Otopike$Distance_um <- Dist

#Check for hickups
Otopike[Otopike$measurement == 1,]$Distance_um

#check
plot(Otopike[Otopike$ID=="#S",]$Distance_um, Otopike[Otopike$ID=="#S",]$d18O, type = "b")

#This isn´t even my final form
Oto_distances <- Otopike %>%
  transmute(ID = ID,
            #ID2 = ID2,
            #measurement=measurement,
            #date = date,
            Distance_um = Distance_um,
            d18O = d18O,
            OH = OH,
            SE_permil = SE_permil)%>%
  group_by(ID)%>%
  arrange(desc(Distance_um))

Oto_distances <- rbind(Oto_distances, Oto_distances2)

write.table(Oto_distances, file = "Otolith_data_2022_clean_core_with_distance_um.txt", dec = ".", sep = ";", row.names = FALSE)
```

```{r automated SIMS plotting, include=FALSE, echo=FALSE, eval=FALSE}
rm(list = ls())

Oto_profiles <- read.delim("Otolith_data_2022_clean_with_distance_um.txt", header = TRUE, dec = ".", sep = ";")

Oto_sizes <- read.delim("Oto_sizes_2022.txt", header = TRUE, stringsAsFactors = F, dec = ".", sep = "\t")
Oto_sizes$Size.x. <- as.numeric(Oto_sizes$Size.x.)
# Oto_sizes$ID <- as.character(substr(Oto_sizes$Otolith, 1,2)) #If OtoID is 01, 02, 03, 04 etc
# Oto_sizes$ID <- as.numeric(Oto_sizes$ID) #If OtoID is 1, 2, 3, 4 etc

png(paste("Sample_2022/#A.png"), width = Oto_sizes[which(Oto_sizes$ID == "#A"), "Size.x.",], 
    height = 0.5 * Oto_sizes[which(Oto_sizes$ID == "#A"), "Size.x.",], units = "px", bg = "black")
par(xaxs = "i", mar = rep(0,4))
plot(Oto_profiles[which(Oto_profiles$ID == "#A"), "Distance_um",], Oto_profiles[Oto_profiles$ID == "#A",]$d18O, main = "", 
     xlab =  "", ylab = "", xlim = c(0, max(Oto_profiles[Oto_profiles$ID == "#A",]$Distance_um)), 
     col.axis = "black", cex.axis = 1.7, type = "b", col = "black", lwd = 3, fg = "black", cex = 4, axes = FALSE)
dev.off()

IDOto <- "F1"
IDOto <- unique(Oto_sizes$ID)
IDOto <- unique(Oto_sizes[which(grepl("#", Oto_sizes$ID)==TRUE),"ID"])#If "special fish" needed

for (i in 1:length(IDOto)) {
  png(paste0("Sample_2022/",IDOto[i], ".png"), width = Oto_sizes[which(Oto_sizes$ID == IDOto[i]), "Size.x.",], 
      height = 0.5 * Oto_sizes[which(Oto_sizes$ID == IDOto[i]), "Size.x.",], units = "px", bg = "black")
  par(xaxs = "i", mar = rep(0,4))
  plot(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "Distance_um",], 
       Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "d18O",], main = "", 
       xlab =  expression(bold("Distance from core"~("\u03bc"~"m"))), ylab = expression(bold("\u03B4"^18*"O"~"otolith"~("VPDB"))), 
       col.axis = "black", cex.axis = 3, type = "b", col = "white", lwd = 4, fg = "black", cex = 3, frame.plot = F, cex.lab = 2)
  box(bty = "l")
  dev.off()  
}
```

```{r pretty plots for presentations, include=FALSE, echo=FALSE, eval=FALSE}
#prettier plots
for (i in 1:length(IDOto)) {
  png(paste0("C:/Users/timor/Nextcloud2/Timo/BODDENHECHT/Geschwafel/Graphic repository/",IDOto[i], "_SIMS_2.png"), 
      width = Oto_sizes[which(Oto_sizes$ID == IDOto[i]), "Size.x.",]+585, #Change "LA-Plots" for whatever 
      height = 0.5 * (Oto_sizes[which(Oto_sizes$ID == IDOto[i]), "Size.x.",]+687), units = "px", bg = "black",
      res = 300)    #path needed 
  par(xaxs = "i", mar = c(12,10,0,0), font.axis=2, font.lab=2)
  plot(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "Distance_um",], 
       Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "d18O",], main = "", 
       xlab =  "", ylab = "", xlim = c(0, max(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "Distance_um",], na.rm = T)), 
       col.axis = "white", cex.axis = 1.7, type = "l", col = "white", lwd = 10, fg = "white", cex = 2, axes = FALSE, pch = 19)
  # axis(1, pos = mean(Oto_profiles[Oto_profiles$ID == IDOto[i],]$d18O), 
  #      at = c(0, max(Oto_profiles[Oto_profiles$ID == IDOto[i],]$Distance_um)),
  #      labels = FALSE, lwd.ticks = 5, tck = 0, col = "white", lty = 1, lwd = 5)
  # axis(1, pos = mean(Oto_profiles$d18O), at = c(0, max(Oto_profiles$Distance_um)),
  #      labels = FALSE, lwd.ticks = 5, tck = 0, col = "white", lty = 3, lwd = 5)
  axis(2, pos = 0, las = 2, mgp = c(0, 2, 2), cex.axis = 3, lwd = 10, col = "white", col.axis = "white",
       at = seq(round(min(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "d18O",], na.rm = T),0),
                round(max(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "d18O",], na.rm = T),0),1),
       labels = seq(round(min(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "d18O",], na.rm = T),0),
                round(max(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "d18O",], na.rm = T),0),1))
  axis(1, pos = -7.8, las = 2, mgp = c(0, 2, 2), cex.axis = 3, lwd = 10, col = "white", col.axis = "white",
       at = seq(0,round(max(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "Distance_um",], na.rm = T),0)+500,500),
       labels = seq(0, round(max(Oto_profiles[which(Oto_profiles$ID == IDOto[i]), "Distance_um",], na.rm = T),0)+500,500))
  title(main = "", ylab = expression(bold("\u03B4"^18*"O"~"otolith"~("VPDB"))),
        cex.lab = 3.5, col.lab = "white", line = 5, font=2)
  title(xlab = expression(bold("Distance from core"~("\u03bc"~"m"))),
        cex.lab = 3.5, col.lab = "white", line = 11, font=2)
  dev.off()  
}

Oto_profiles[Oto_profiles$ID=="#D",]$d18O
```

```{r prepare annuli file, include=FALSE, echo=FALSE, eval=FALSE}

rm(list = ls())

#load annuli
annuli <- read.delim("Sample_2022/Aging/Sample_2022_oto_annuli.txt", sep = "\t", header = T, 
                   stringsAsFactors = F)

#Extract BH-numbers from sample names (ObjectJ)
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

annu <- annuli%>%
 group_by(Sample)%>%
 mutate(inc = case_when(I %in% "core"~"0",
                         I %in% "edge"~as.character(length(unique(I))-1),
                         TRUE~I))%>%
 ungroup()%>%
 transmute(fishID = substrRight(Sample, 8),
           simsID = gsub("_", "",substr(Sample,0,2)),
           quality = Quality,
           age = Age,
           cohort = Cohort,
           core = Core,
           inc = inc,
           year = Year,
           increment_um = case_when(inc %in% "0"~0,
                                    TRUE ~ as.numeric(Increment)))

annu <- data.frame(annu)
IDpike <- unique(annu$fishID)
rad <- NULL
for (i in 1:length(IDpike)) {
 d <- cumsum(coalesce(annu[which(annu$fishID == IDpike[i]), "increment_um"], 0)) + annu[which(annu$fishID == IDpike[i]), "increment_um"]*0
 rad <- c(rad, d)
}

annu$rad <- rad

annu$inc <- as.numeric(annu$inc)

#Change annu ID to match SIMS IDs
#annu$simsID <- paste0("#", annu$simsID)

annu <- annu%>%
 transmute(simsID = simsID,
           fishID = fishID,
           quality = quality,
           age = age,
           cohort = cohort,
           core = core,
           year = inc,
           yearclass = year,
           increment_um = increment_um,
           rad_um = rad)

write.table(annu, "Sample_2022/annuli_with_rad.txt", sep = "\t", dec = ".", row.names = F)
```

```{r divide SIMS data into years, include=FALSE, echo=FALSE, eval=FALSE}
rm(list = ls())

#Read newest annu file
annu <- read.delim("Sample_2021/annuli_with_rad.txt", header = T, stringsAsFactors = F, sep = "\t", dec = ".")


#load SIMS data
sims <- fread("Sample_2021/Otolith_data_2021_clean_core_with_distance_um.csv")
names(sims) <- tolower(names(sims))

#inverse order for distances
sims <- sims %>% group_by(id)%>%arrange(distance_um, by_group = F)%>%ungroup()%>%
  arrange(id)

#remove 34
#sims <- sims[grepl("34", sims$id)==F,]

#select Pilot fish
sims <- sims%>%filter(id%in%unique(annu$simsID)==TRUE)

#fish list
PikeDB <- read.delim("1Pike_Latest_Version.txt", sep = ";", dec = ".", header = T, stringsAsFactors = F)
fishdata <- PikeDB%>%
  transmute(fishID=case_when(Fish_ID=="BH-91050.2"~"BH-91050",
                             Fish_ID=="BH-51614"&Waterbody=="BAT"~"NA",
                         TRUE~Fish_ID),
            cdate=Date,
            TL_mm = Total_Length_mm,
            Weight=Weight,
            sex=Sex,
            area=Waterbody)

#correct annu placement
# ID <-"BH-93178"
# x <- 1
# y <- 10

# annu[annu$fishID == ID & annu$year == x,]$rad_um <- annu[annu$fishID == ID & annu$year == x,]$rad_um+y
# annu[annu$fishID == ID & annu$year == x,]$increment_um <- annu[annu$fishID == ID & annu$year == x,]$increment_um+y

#If you need to change the age of a fish
# annu[annu$fishID == ID & annu$year == 2,]$rad_um <- annu[annu$fishID == ID & annu$year == 2,]$rad_um
# annu[annu$fishID == ID & annu$year == 2,]$increment_um <- annu[annu$fishID == ID & annu$year == 2,]$increment_um+annu[annu$fishID == ID & annu$year == 1,]$increment_um
# 
# annu[annu$fishID == ID & annu$year == 2,]$year <- 1
# annu[annu$fishID == ID & annu$yearclass == 2,]$yearclass <- 1
# 
# annu[annu$fishID == ID & annu$year == 3,]$year <- 2
# annu[annu$fishID == ID & annu$yearclass == 3,]$yearclass <- 2
# 
# annu[annu$fishID == ID & annu$year == 4,]$year <- 3
# annu[annu$fishID == ID & annu$yearclass == 4,]$yearclass <- 3
# 
# annu[annu$fishID == ID & annu$year == 5,]$year <- 4
# annu[annu$fishID == ID & annu$yearclass == 5,]$yearclass <- 4
# 
# annu[annu$fishID == ID & annu$year == 6,]$year <- 5
# annu[annu$fishID == ID & annu$yearclass == 6,]$yearclass <- 5
# 
# annu[annu$fishID == ID & annu$year == 7,]$year <- 6
# annu[annu$fishID == ID & annu$yearclass == 7,]$yearclass <- 6
# 
# annu[annu$fishID == ID,]$age <- 5

#Loop to break into years
IDpike <- unique(sims$id)
radID <- unique(annu$year)
y <- NULL
yy <- NULL

for (i in 1:length(IDpike)) {
  for (j in 0:length(annu[which(annu$simsID==IDpike[i]), "year"])) {
y <- ifelse(sims[which(sims$id==IDpike[i]), "distance_um"]<=
                      annu[which(annu$simsID==IDpike[i]&annu$year==radID[j]), "rad_um"]&
              sims[which(sims$id==IDpike[i]), "distance_um"]
              >=annu[which(annu$simsID==IDpike[i]&annu$year==radID[j-1]), "rad_um"],
                    annu[which(annu$simsID==IDpike[i]&annu$year==radID[j]), "year"],
            ifelse(sims[which(sims$id==IDpike[i]), "distance_um"]>
              max(annu[which(annu$simsID==IDpike[i]), "rad_um"])&
                radID[j]==max(annu[which(annu$simsID==IDpike[i]), "year"]), 
            max(annu[which(annu$simsID==IDpike[i]), "year"]),NA))
yy <- c(yy, na.omit(y))
  }
}

##revert the order of distances in "sims", so the yy vector can be pasted correctly

str_sort(unique(sims$id))
str_sort(unique(annu$simsID))

sims$year <- yy

#prepare join with pike data
sims2 <- sims%>%
  group_by(id)%>%
  ungroup()%>%
  transmute(simsID = id,
            d18O = d18o,
            distance_um = distance_um,
            year = year)

pikedata <- annu%>%
  inner_join(sims2, by = c("simsID", "year"))

pikedata_all <- pikedata%>%
  inner_join(fishdata, by = "fishID")

pike_d18O <- pikedata_all%>%
  transmute(ID = fishID,
            TL_mm = TL_mm,
            weight = Weight,
            sex = sex,
            area = area,
            capt_date = cdate,
            age = age,
            cohort = cohort,
            year = year,
            inc_um = increment_um,
            rad_um = rad_um,
            core = core,
            d18O = d18O,
            sims_dist = distance_um)

#d18O plots
IDOto <- unique(pike_d18O$ID)

for (i in 1:length(IDOto)) {
  png(paste0("Sample_2022/Test_plots/d18O/", IDOto[i], "_d18O.png"))
  plot(pike_d18O[which(pike_d18O$ID == IDOto[i]), "sims_dist",], 
       pike_d18O[which(pike_d18O$ID == IDOto[i]), "d18O",], main = "", 
       xlab =  "", ylab = "", xlim = c(0, max(pike_d18O[which(pike_d18O$ID == IDOto[i]), "sims_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "b", col = "black", lwd = 2, fg = "black", cex = 1, axes = T, pch = 19)
  abline(v = c(pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 1), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 2), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 3), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 4), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 5), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 6), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 7), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 8), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 9), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 10), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 11), "rad_um"])) 
  title(main = "", ylab = "d18O", cex.lab = 15, col.lab = "black", line = 30)
  dev.off()  
}

#save annu as table to change the distances
#write.table(annu, "Sample_2022/annuli_with_rad.txt", sep = "\t", dec = ".", row.names = F)
```

```{r save d18O data, include=FALSE, echo=FALSE, eval=FALSE}
#prepare join with pike data
sims2 <- sims%>%
  group_by(id)%>%
  #mutate(fishID2 = id2[2])%>%
  ungroup()%>%
  transmute(simsID = id,
            #fishID = fishID2,
            d18O = d18o,
            distance_um = distance_um,
            year = year)

pikedata <- annu%>%
  inner_join(sims2, by = c("simsID", "year"))

pikedata_all <- pikedata%>%
  inner_join(fishdata, by = "fishID")

pike_d18O <- pikedata_all%>%
  transmute(ID = fishID,
            TL_mm = TL_mm,
            weight = Weight,
            sex = sex,
            area = area,
            capt_date = cdate,
            age = age,
            cohort = cohort,
            year = year,
            inc_um = increment_um,
            rad_um = rad_um,
            core = core,
            d18O = d18O,
            sims_dist = distance_um)

#remove BH-01741 (vaterite)
#pike_d18O <- pike_d18O%>%filter(ID!="BH-01741")

#save table
write.table(pike_d18O, "Sample_2022/pike_data_2022_d18O_years.txt", sep = "\t", 
            dec = ".", row.names = F)
#all fish have an edge increment that is counted as a year, only for fish caught between
#01.01 and 31.04 this should be actually counted as year
```

```{r divide trace elements into years, include=FALSE, echo=FALSE, eval=FALSE}

rm(list = ls())

#load pike data
PikeDB <- read.delim("1Pike_Latest_Version.txt", sep = ";", dec = ".", header = T, stringsAsFactors = F)
fishdata <- PikeDB%>%
  transmute(fishID=case_when(Fish_ID=="BH-91050.2"~"BH-91050",
                             Fish_ID=="BH-51614"&Waterbody=="BAT"~"NA",
                         TRUE~Fish_ID),
            cdate=Date,
            TL_mm = Total_Length_mm,
            Weight=Weight,
            sex=Sex,
            area=Waterbody)

#load annuli
annu <- read.delim("Pilot/annuli_with_rad.txt", header = T, stringsAsFactors = F, sep = "\t", dec = ".")


#load trace elements
elements <- read.delim("Pilot/Otolith_LA-data_Pilot_with_distance.txt", sep = "\t", 
                       header = T, stringsAsFactors = F)
#elements <- elements%>%filter(Mount == "Pilot")
names(elements) <- tolower(names(elements))

#elements[elements$sims_id=="F2",]$sims_id <- NA

#sort IDs to be able to compare if someones missing
# A <- str_sort(unique(elements$ID))
# B <- str_sort(unique(elements2$Fish_ID))
# 
# AB <- data.frame(ID=B)
# BA <- data.frame(ID=A, ID2=A)
# ABC <- AB%>%left_join(BA, by="ID")

#elements$sims_id <- paste0("#", substr(elements$sims_id, 0,1))

elements <- elements%>%filter(fish_id%in%annu$fishID==TRUE)

#inverse order for distances
elements <- elements %>% group_by(fish_id)%>%arrange(distance_um, by_group = F)%>%ungroup()%>%
  arrange(fish_id)


#remove 34
#elements <- elements[grepl("34", elements$sims_id)==F,]

#Loop to break into years
IDpike <- unique(elements$fish_id)
radID <- unique(annu$year)
y <- NULL
yy <- NULL

for (i in 1:length(IDpike)) {
  for (j in 0:length(annu[which(annu$fishID==IDpike[i]), "year"])) {
y <- ifelse(elements[which(elements$fish_id==IDpike[i]), "distance_um"]<
                      annu[which(annu$fishID==IDpike[i]&annu$year==radID[j]), "rad_um"]&
              elements[which(elements$fish_id==IDpike[i]), "distance_um"]
              >=annu[which(annu$fishID==IDpike[i]&annu$year==radID[j-1]), "rad_um"],
                    annu[which(annu$fishID==IDpike[i]&annu$year==radID[j]), "year"],
            ifelse(elements[which(elements$fish_id==IDpike[i]), "distance_um"]>
              max(annu[which(annu$fishID==IDpike[i]), "rad_um"])&
                radID[j]==max(annu[which(annu$fishID==IDpike[i]), "year"]), 
            max(annu[which(annu$fishID==IDpike[i]), "year"]),NA))
yy <- c(yy, na.omit(y))
  }
}

elements$year <- yy

#prepare join
elements <- elements%>%
  transmute(simsID = sims_id,
            fishID = fish_id,
            Sr = sr.ca,
            Na = na.ca,
            Mg = mg.ca,
            Ba = ba.ca,
            Mn = mn.ca,
            distance_um = distance_um,
            year = year)

pikedata <- annu%>%
  inner_join(elements, by = c("fishID", "year"))

pikedata_all <- pikedata%>%
  inner_join(fishdata, by = "fishID")

pike_LA_data <- pikedata_all%>%
  transmute(ID = fishID,
            TL_mm = TL_mm,
            weight = Weight,
            sex = sex,
            area = area,
            capt_date = cdate,
            age = age,
            cohort = cohort,
            year = year,
            inc_um = increment_um,
            rad_um = rad_um,
            core = core,
            Sr = Sr,
            Na = Na,
            Mg = Mg,
            Ba = Ba,
            Mn = Mn,
            LA_dist = distance_um)


#preliminary save
write.table(pike_LA_data, "Pilot/pike_data_LA-ICPMS_Pilot_years_with_core.txt", sep = "\t", 
            dec = ".", row.names = F)
```

```{r check elements, include=FALSE, echo=FALSE, eval=FALSE}
#script to plot each pike d18O & Sr/Ca plot into .png & compare them with annual
#rings on pictures

rm(list = ls())

#load d18O data
pike_d18O <- fread("Sample_2022/pike_data_2022_d18O_years.txt")

#load LA-ICPMS data
pike_elements <- fread("Sample_2022/pike_data_LA-ICPMS_2023_years_with_core.txt")

IDOto <- unique(pike_elements$ID)

pike_d18O <- as.data.frame(pike_d18O)
pike_elements <- as.data.frame(pike_elements)

#IDOto <- "BH-00355"

#All element plots
for (i in 1:length(IDOto)) {
  png(paste0("Sample_2022/Test_plots/Elements/", IDOto[i], "_Sr.png"), width = 1200, height = 1200)
  par(mfrow=c(6,1))
  #d18O
  plot(pike_d18O[which(pike_d18O$ID == IDOto[i]), "sims_dist",], 
       pike_d18O[which(pike_d18O$ID == IDOto[i]), "d18O",], main = "d18O",
       xlab =  "", ylab = "", xlim = c(0, max(pike_d18O[which(pike_d18O$ID == IDOto[i]), "sims_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "b", col = "black", lwd = 2, fg = "black", cex = 2, axes = T, pch = 19)
  abline(v = c(pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 1), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 2), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 3), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 4), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 5), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 6), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 7), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 8), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 9), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 10), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 11), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 12), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 13), "rad_um"]))
  mtext(pike_d18O[which(pike_d18O$ID == IDOto[i]),]$area, side = 3, line = 1, at = 0)
  #Sr
  plot(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], 
       pike_elements[which(pike_elements$ID == IDOto[i]), "Sr",], main = "Sr/Ca", ylim = c(0,0.007),
       xlab =  "", ylab = "", xlim = c(0, max(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "l", col = "black", lwd = 1, fg = "black", cex = 2, axes = T, pch = 19)
  abline(v = c(pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 1), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 2), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 3), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 4), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 5), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 6), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 7), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 8), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 9), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 10), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 11), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 12), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 13), "rad_um"])) 
  #Na
  title(main = "", ylab = "Sr/Ca", cex.lab = 15, col.lab = "black", line = 30)
  plot(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], 
       pike_elements[which(pike_elements$ID == IDOto[i]), "Na",], main = "Na/Ca", 
       xlab =  "", ylab = "", xlim = c(0, max(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "l", col = "black", lwd = 1, fg = "black", cex = 2, axes = T, pch = 19)
  abline(v = c(pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 1), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 2), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 3), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 4), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 5), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 6), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 7), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 8), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 9), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 10), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 11), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 12), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 13), "rad_um"]))
  #Mg
  plot(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], 
       pike_elements[which(pike_elements$ID == IDOto[i]), "Mg",], main = "Mg/Ca", 
       xlab =  "", ylab = "", xlim = c(0, max(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "l", col = "black", lwd = 1, fg = "black", cex = 2, axes = T, pch = 19)
  abline(v = c(pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 1), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 2), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 3), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 4), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 5), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 6), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 7), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 8), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 9), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 10), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 11), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 12), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 13), "rad_um"])) 
  #Ba
  plot(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], 
       pike_elements[which(pike_elements$ID == IDOto[i]), "Ba",], main = "Ba/Ca", 
       xlab =  "", ylab = "", xlim = c(0, max(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "l", col = "black", lwd = 1, fg = "black", cex = 2, axes = T, pch = 19)
  abline(v = c(pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 1), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 2), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 3), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 4), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 5), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 6), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 7), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 8), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 9), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 10), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 11), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 12), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 13), "rad_um"]))
  #Mn
  plot(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], 
       pike_elements[which(pike_elements$ID == IDOto[i]), "Mn",], main = "Mn/Ca", 
       xlab =  "", ylab = "", xlim = c(0, max(pike_elements[which(pike_elements$ID == IDOto[i]), "LA_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "l", col = "black", lwd = 1, fg = "black", cex = 2, axes = T, pch = 19)
  abline(v = c(pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 1), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 2), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 3), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 4), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 5), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 6), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 7), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 8), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 9), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 10), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 11), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 12), "rad_um"],
               pike_elements[which(pike_elements$ID == IDOto[i]&
                             pike_elements$year == 13), "rad_um"]))
  dev.off()  
}
```

```{r group & save d18O data, include=FALSE, echo=FALSE, eval=FALSE}

rm(list = ls())

Pike1 <- read.delim("1Pike_Latest_Version.txt", sep = ";", dec = ".", header = T, stringsAsFactors = F)
Pike2 <- Pike1%>%
  transmute(ID=case_when(Fish_ID=="BH-91050.2"~"BH-91050",
                         Fish_ID=="BH-51614"&Waterbody=="BAT"~"NA",
                         Fish_ID=="BH-90307"&MarkorRecap=="Mark"~"NA",
                         TRUE~Fish_ID),
            capt_date=Date,
            TL_mm = Total_Length_mm,
            Weight=Weight,
            sex=Sex,
            area=Waterbody)

Recap <- Pike1[Pike1$Fish_ID=="BH-90307",]

#read in 2021 data d18O
pike_d18O_21 <- read.delim("Sample_2021/pike_data_d18O_years.txt", header = T, stringsAsFactors = F, sep = "\t", dec = ".")

#read in Pilot data d18O
pike_d18O_Pilot <- read.delim("Pilot/pike_data_pilot_d18O_years.txt", header = T, stringsAsFactors = F, sep = "\t", dec = ".")
pike_d18O_Pilot <- pike_d18O_Pilot%>%filter(ID!="BH-00670")

#read in 2022 data d18O
pike_d18O_22 <- read.delim("Sample_2022/pike_data_2022_d18O_years.txt", header = T, stringsAsFactors = F, sep = "\t", dec = ".")

#join
pike_d18O_all_years <- rbind(pike_d18O_Pilot, pike_d18O_21, pike_d18O_22)

#all there? (130)
SIMSpike <- read.delim("Scales_Oto_data.txt", header = T, stringsAsFactors = F, sep = "\t", dec = ".")
SIMSpike <- SIMSpike%>%
  transmute(ID=substr(ID, 1,8),
            capt_date=date,
            TL_mm = TL,
            Weight=Weight,
            sex=sex,
            area=area)

Joinpike <- SIMSpike%>%
  left_join(Pike2, by= "ID")%>%
  left_join(pike_d18O_all_years, by= "ID")

Alldata <- Joinpike%>%
  transmute(fishID=ID,
            capt_date=capt_date.x,
            TL_mm=TL_mm.y,
            weight=Weight.y,
            sex=sex.y,
            area=area.y,
            age=age,
            cohort=cohort,
            lifeyear=year,
            inc_um=inc_um,
            rad_um=rad_um,
            core=core,
            sims_dist=sims_dist,
            d18O=d18O,
            comment=case_when(fishID=="BH-01701"~"Missplaced transect",
                              fishID=="BH-01741"~"Vaterite",
                              fishID=="BH-01908"~"Vaterite",
                              fishID=="BH-90962"~"Lost",
                              fishID=="BH-93190"~"no SIMS",
                              TRUE~"OK"))%>%
  distinct()

#check
# IDOto <- unique(pike_d18O_all_years$ID)
# 
# for (i in 1:length(IDOto)) {
#   png(paste0("d18O-plots/", IDOto[i], "_d18O.png"))
#   plot(Alldata[which(Alldata$fishID == IDOto[i]), "sims_dist",], 
#        Alldata[which(Alldata$fishID == IDOto[i]), "d18O",], main = "", 
#        xlab =  "", ylab = "", xlim = c(0, max(Alldata[which(Alldata$fishID == IDOto[i]), "sims_dist",], na.rm = T)), 
#        col.axis = "black", cex.axis = 1.7, type = "b", col = "black", lwd = 2, fg = "black", cex = 1, axes = T, pch = 19)
#   abline(v = c(Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 1), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 2), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 3), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 4), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 5), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 6), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 7), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 8), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 9), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 10), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 11), "rad_um"])) 
#   title(main = "", ylab = "d18O", cex.lab = 15, col.lab = "black", line = 30)
#   dev.off()  
# }

#Test length
length(unique(Alldata$fishID))

#save table

write.table(Alldata, "Pike-d18O-years_whole-sample_with-TL.txt", sep = "\t", 
            dec = ".", row.names = F)
```

```{r group LA data together with main sample, include=FALSE, echo=FALSE, eval=FALSE}
rm(list = ls())

Pike1 <- read.delim("1Pike_Latest_Version.txt", sep = ";", dec = ".", header = T, stringsAsFactors = F)
Pike2 <- Pike1%>%
  transmute(ID=case_when(Fish_ID=="BH-91050.2"~"BH-91050",
                         Fish_ID=="BH-51614"&Waterbody=="BAT"~"NA",
                         Fish_ID=="BH-90307"&MarkorRecap=="Mark"~"NA",
                         TRUE~Fish_ID),
            capt_date=Date,
            TL_mm = Total_Length_mm,
            Weight=Weight,
            sex=Sex,
            area=Waterbody)

#Load Pilot element transects
Pilot <- read.delim("Pilot/pike_data_LA-ICPMS_Pilot_years_with_core.txt", 
                    header = T, stringsAsFactors = F, 
                      sep = "\t", dec = ".")
Pilot <- Pilot%>%filter(ID!="BH-00670")

#Load 2021 element transects
LA_2021 <- read.delim("Sample_2021/pike_data_LA-ICPMS_2021_years_with_core.txt", header = T, stringsAsFactors = F, 
                      sep = "\t", dec = ".")

#Load 2022 element transects
LA_2022 <- read.delim("Sample_2022/pike_data_LA-ICPMS_2023_years_with_core.txt")

#check names before join
names(LA_2021)==names(LA_2022)
names(LA_2021)==names(Pilot)

#join
LA_All <- rbind(Pilot,LA_2021, LA_2022)

#Look for missing fish
Joindata <- read.delim("Pike-d18O-years_whole-sample_with-TL.txt", header = T, stringsAsFactors = F,
                      sep = "\t", dec = ".")

LA_ID <- data.frame(ID=unique(LA_All$ID), ID2=unique(LA_All$ID))

Pike_ID <- data.frame(ID=unique(Joindata$fishID))

Missing <- Pike_ID%>%left_join(LA_ID, by = "ID")

#Join
Join <- Joindata%>%
  transmute(ID=fishID,
            capt_date=capt_date,
            TL_mm=TL_mm,
            weight=weight,
            sex=sex,
            area=area,
            age=age,
            cohort=cohort,
            comment=comment)%>%
  distinct()

LA_join <- LA_All%>%
  transmute(ID=ID,
            lifeyear=year,
            inc_um=inc_um,
            rad_um=rad_um,
            core=core,
            LA_dist=LA_dist,
            Sr=Sr,
            Na=Na,
            Mg=Mg,
            Ba=Ba,
            Mn=Mn)

Alldata <- Join%>%left_join(LA_join, by="ID")%>%
  transmute(fishID=ID,
            capt_date=capt_date,
            TL_mm=TL_mm,
            weight=weight,
            sex=sex,
            area=area,
            age=age,
            cohort=cohort,
            lifeyear=lifeyear,
            inc_um=inc_um,
            rad_um=rad_um,
            core=core,
            LA_dist=LA_dist,
            Sr=Sr,
            Na=Na,
            Mg=Mg,
            Ba=Ba,
            Mn=Mn,
            comment=comment)%>%
  distinct()

#Check & save
# IDOto <- unique(LA_All$ID)
# 
# for (i in 1:length(IDOto)) {
#   png(paste0("Sr-plots/", IDOto[i], "_Sr.png"))
#   plot(Alldata[which(Alldata$fishID == IDOto[i]), "LA_dist",], 
#        Alldata[which(Alldata$fishID == IDOto[i]), "Sr",], main = "", 
#        xlab =  "", ylab = "", xlim = c(0, max(Alldata[which(Alldata$fishID == IDOto[i]), "LA_dist",], na.rm = T)), 
#        col.axis = "black", cex.axis = 1.7, type = "b", col = "black", lwd = 2, fg = "black", cex = 1, axes = T, pch = 19)
#   abline(v = c(Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 1), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 2), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 3), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 4), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 5), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 6), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 7), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 8), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 9), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 10), "rad_um"],
#                Alldata[which(Alldata$fishID == IDOto[i]&
#                              Alldata$lifeyear == 11), "rad_um"])) 
#   title(main = "", ylab = "d18O", cex.lab = 15, col.lab = "black", line = 30)
#   dev.off()  
# }

#Turn wrong distances around (backcheck for 00355, 00405, 01776, 01877, 00689(unchanged), 01774(unchanged))

# Alldata[Alldata$fishID=="BH-01877",]$LA_dist <- seq(max(Alldata[Alldata$fishID=="BH-01877",]$LA_dist),0,by = -5.5)

write.table(Alldata, "Pike-LA-ICPMS-years_whole-sample_with-TL.txt", sep = "\t", 
            dec = ".", row.names = F)

```


